import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Clerk } from "@clerk/nextjs/server";
import { ThemeProvider } from "@/components/providers/theme-provider";


import { riloSBold,riloLight } from "@/style/fonts/rilo";
import { jersey } from "@/style/fonts/jersey";
import { Variable } from "lucide-react";
import { ModalProvider } from "@/components/providers/modal-provider";

const inter = Inter({ subsets: ["latin"] ,variable : '--font-inter'});


export const metadata: Metadata = {
  title: "Straight to Rizzing",
  description: "Generated by Mahil",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.variable} ${jersey.variable} ${riloSBold.variable} ${riloLight.variable}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storage-key="rizzcord-theme"
          >
            <ModalProvider />
            {children}
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
